name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            if [ ! -d "/home/deploy/money-way" ]; then
              git clone https://github.com/USERNAME/REPO.git /home/deploy/money-way
            fi
            cd /home/deploy/money-way
            git pull
            chmod +x gradlew
            ./gradlew build -x test
            sudo systemctl restart money-way.service
