name: Deploy to VPS

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_KEY }}
          script: |
            if [ ! -d "/home/deploy/money-way" ]; then
              git clone https://github.com/OWNER/REPO.git /home/deploy/money-way
            fi
            cd /home/deploy/money-way
            git pull
            chmod +x gradlew
            ./gradlew build -x test

            LATEST_JAR=$(ls -1t build/libs/*.jar | head -n1)
            ln -sf "$LATEST_JAR" app.jar

            sudo systemctl daemon-reload
            sudo systemctl restart money-way.service
